name: inverted_pendulum
channels:
- http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
- http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
- defaults
dependencies:
- bzip2=1.0.8=h1de35cc_0
- certifi=2022.12.7=py310hecd8cb5_0
- cffi=1.15.1=py310h6c40b1e_3
- flit-core=3.6.0=pyhd3eb1b0_0
- future=0.18.2=py310hecd8cb5_1
- mkl-service=2.4.0=py310hca72f7f_0
- mkl_fft=1.3.1=py310hf879493_0
- mkl_random=1.2.2=py310hc081a56_0
- numpy=1.23.5=py310h9638375_0
- numpy-base=1.23.5=py310ha98c3c9_0
- pip=22.3.1=py310hecd8cb5_0
- pycparser=2.21=pyhd3eb1b0_0
- python=3.10.9=h218abb5_0
- pytorch=1.12.1=cpu_py310h64f2f56_1
- pyyaml=6.0=py310h6c40b1e_1
- setuptools=65.6.3=py310hecd8cb5_0
- six=1.16.0=pyhd3eb1b0_1
- typing-extensions=4.4.0=py310hecd8cb5_0
- typing_extensions=4.4.0=py310hecd8cb5_0
- tzdata=2022g=h04d1e81_0
- wheel=0.38.4=py310hecd8cb5_0
- blas=1.0=mkl
- ninja=1.7.2=0
- ca-certificates=2023.01.10=hecd8cb5_0
- intel-openmp=2021.4.0=hecd8cb5_3538
- libcxx=14.0.6=h9765a3e_0
- libffi=3.4.2=hecd8cb5_6
- libgfortran=5.0.0=11_3_0_hecd8cb5_28
- libgfortran5=11.3.0=h9dfd629_28
- libopenblas=0.3.21=h54e7dc3_0
- libprotobuf=3.20.3=hfff2838_0
- libuv=1.40.0=haf1e3a3_0
- llvm-openmp=14.0.6=h0dcd299_0
- mkl=2021.4.0=hecd8cb5_637
- ncurses=6.4=hcec6c5f_0
- openssl=1.1.1t=hca72f7f_0
- readline=8.2=hca72f7f_0
- sqlite=3.40.1=h880c91c_0
- tk=8.6.12=h5d9f67b_0
- xz=5.2.10=h6c40b1e_1
- yaml=0.2.5=haf1e3a3_0
- zlib=1.2.13=h4dc903c_0
prefix: /Users/wangguojian/anaconda2/envs/inverted_pendulum

